services:
  db:
    image: postgres:14
    volumes:
      nchain-example:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nchain
      - POSTGRES_USER=nchain
      - POSTGRES_PASSWORD=nchain
    ports:
      - 5432:5432
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  nchain-example: {}